version: '3.8'

services:
  finnex:
    image: emaijala/mlinvoice:latest
    container_name: finnex
    ports:
      - "8081:80"
    volumes:
      - ./:/usr/local/mlinvoice
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=mlinvoice_root
      - MYSQL_DATABASE=mlinvoice
      - MYSQL_USER=mlinvoice
      - MYSQL_PASSWORD=mlinvoice_pass
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10
    container_name: finnex_db
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=mlinvoice_root
      - MYSQL_DATABASE=mlinvoice
      - MYSQL_USER=mlinvoice
      - MYSQL_PASSWORD=mlinvoice_pass
    restart: unless-stopped

volumes:
  db_data:
